# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-08 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('nickname', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('token', models.CharField(max_length=256)),
                ('create_time', models.CharField(max_length=128)),
                ('update_time', models.CharField(max_length=128)),
            ],
        ),
    ]
